### ISSUE TITLE
`SoundCloudTrack` Always Raises `BadArgument`

### ISSUE THREAD

**Issue by Makiyu-py** [Pycord-Development/Pycord.Wavelink#13]
### Summary

Every time I search for a song in SoundCloud with `wavelink.SoundCloudTrack`, it never returns anything. Rather, it raises a `BadArgument` exception stating that it could not find any songs matching that query.

### Reproduction Steps

1. Run the Minimal Reproducible Code
2. Join a VC that your bot can join
3. Run the `play` command with your query of choice

### Minimal Reproducible Code

Use the example code but replace the type annotation for the `search` argument from `wavelink.YouTubeTrack` to `wavelink.SoundCloudTrack`.

### Expected Results

The bot would join the VC and play the song from a lavalink server's SoundCloud search with the query

### Actual Results

```
Ignoring exception in command play:
Traceback (most recent call last):
  File "ProjectDir/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 335, in invoke
    await ctx.command.invoke(ctx)
  File "ProjectDir/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 902, in invoke
    await self.prepare(ctx)
  File "ProjectDir/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 832, in prepare
    await self._parse_arguments(ctx)
  File "ProjectDir/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 747, in _parse_arguments
    kwargs[name] = await self.transform(ctx, param)
  File "ProjectDir/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 590, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
  File "ProjectDir/venv/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 1183, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
  File "ProjectDir/venv/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 1075, in _actual_conversion
    return await converter.convert(ctx, argument)
  File "ProjectDir/pycord/wavelink/tracks.py", line 203, in convert
    raise commands.BadArgument("Could not find any songs matching that query.")
discord.ext.commands.errors.BadArgument: Could not find any songs matching that query.
```

### Intents

None

### System Information

Since I couldn't install the latest version, I, instead, cloned this repository to the latest commit (edaf4d7caedf797852d82d3e08faec9d89997ab7) and dragged the source code (the `pycord` directory inside of `src`) to the root project directory.
```
- Python 3.8.5
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4688+g52fdbb1b
- aiohttp v3.7.4.post0
- system information: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
```

**Comment by Makiyu-py** [comment]
weird, works now for some reason
